name: Docker Build and Test

on:
  push:
    branches: [ main, pet-registration-with-qr ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Create .env file
      run: |
        cp .env.example .env
        echo "JWT_SECRET=test-jwt-secret-for-ci-cd-pipeline" >> .env

    - name: Build Docker images
      run: |
        docker-compose build

    - name: Start services
      run: |
        docker-compose up -d

    - name: Wait for services to be ready
      run: |
        echo "Waiting for services to start..."
        sleep 30

    - name: Check service health
      run: |
        docker-compose ps
        curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:5000/ || exit 1
        curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:3000/ || exit 1

    - name: View logs on failure
      if: failure()
      run: |
        docker-compose logs

    - name: Stop services
      if: always()
      run: |
        docker-compose down -v
